import { Button, HorizontalBox, LineEdit, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {

    default-font-size: 20px;

    in property <string> status; // last DB update etc.
    in property <string> search_error;
    callback request-increase-value();
    callback download-db();
    callback search(string);

    VerticalBox {
        alignment: start;
        HorizontalBox {
            searchLineEdit := LineEdit {
                placeholder-text: "Enter search string";
                accepted(text) => {
                    root.search(text);
                }
            }
            Button {
                icon: @image-url("icons/search.svg");
                colorize-icon: true;
                clicked => {
                    root.search(searchLineEdit.text);
                }
            }
        }
        if searchLineEdit.text.is-empty : HorizontalBox {
            HorizontalBox {
                alignment: start;
                Text {
                    text: "\{root.status}";
                    vertical-alignment: center;
                }

                Button {
                    icon: @image-url("icons/reload.png");
                    clicked => {
                        root.download-db();
                    }
                }
            }
        }
        if !search_error.is-empty : Text {
            text: search_error;
        }
    }
}
