import { Button, HorizontalBox, LineEdit, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {

    default-font-size: 20px;

    in property <string> status;
    callback request-increase-value();
    callback download-db();
    callback search(string);

    VerticalBox {
        HorizontalBox {
            searchLineEdit := LineEdit {
                placeholder-text: "Enter search string";
                accepted(text) => {
                    root.search(text);
                }
            }
            Button {
                icon: @image-url("icons/search.svg");
                colorize-icon: true;
                clicked => {
                    root.search(searchLineEdit.text);
                }
            }
        }
        if searchLineEdit.text.is-empty : HorizontalBox {
            HorizontalBox {
                Text {
                    text: "\{root.status}";
                }

                Button {
                    text: "Download database";
                    clicked => {
                        root.download-db();
                    }
                }
            }
        }
    }
}
