import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {

    default-font-size: 20px;

    in-out property <int> counter: 42;
    callback request-increase-value();
    callback download-db();

    VerticalBox {
        Text {
            text: "Videofinder";
        }
        Text {
            text: "Counter: \{root.counter}";
        }

        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }
	Button {
	    text: "Download database";
	    clicked => {
	        root.download-db();
            }
        }
    }
}
